import test from 'node:test';import assert from 'node:assert/strict';
import {runConsensus,approve,approvalsMatch,approvalsStillValid,canRelease,sha256} from '../dist/packages/consensus-engine/src/index.js';
import {MockAgent} from '../dist/packages/provider-adapters/src/index.js';
const context={brief:'A serious analytics UI',criteria:['accessibility','consistency'],baseVersion:'0.1.0'};
function proposal(id,author,value){return {id,author,baseVersion:'0.1.0',summary:'x',changes:[{path:'tokens.radius',value}],tradeoffs:[],unresolved:[]};}
test('initial proposals are independent and cross-review converges',async()=>{const a=new MockAgent('astra',{initial:proposal('A','astra','8px'),convergeTo:{'tokens.radius':'10px'}});const f=new MockAgent('fable',{initial:proposal('F','fable','12px'),convergeTo:{'tokens.radius':'10px'}});const r=await runConsensus({astra:a,fable:f,context});assert.equal(r.status,'CONSENSUS');assert.equal(r.critiques.length,2);assert.equal(a.seenInitialContexts.length,1);assert.equal(f.seenInitialContexts.length,1);assert.equal('proposal' in a.seenInitialContexts[0],false);});
test('deadlock terminates at configured round limit',async()=>{const a=new MockAgent('astra',{initial:proposal('A','astra','8px')});const f=new MockAgent('fable',{initial:proposal('F','fable','12px')});const r=await runConsensus({astra:a,fable:f,context,maxRounds:2});assert.equal(r.status,'DEADLOCK');assert.equal(r.rounds,2);assert.ok(r.conflicts.length>0);});
test('same hash approvals and human gate are enforced',async()=>{const candidate={baseVersion:'0.1.0',changes:[{path:'a',value:1}]};const hash=await sha256(candidate);const approvals=[approve('astra',hash),approve('fable',hash)];assert.equal(approvalsMatch(hash,approvals),true);assert.equal(canRelease({candidateHash:hash,approvals,humanApproved:false}),false);assert.equal(canRelease({candidateHash:hash,approvals,humanApproved:true}),true);});
test('candidate mutation invalidates approvals',async()=>{const c={baseVersion:'0.1.0',changes:[{path:'a',value:1}]};const h=await sha256(c);const approvals=[approve('astra',h),approve('fable',h)];const mutated={...c,changes:[{path:'a',value:2}]};assert.equal(await approvalsStillValid(mutated,approvals),false);});
