/* global document, location, history */
import {summarizeCoverage,describeTarget} from './coverage.mjs';
const $=id=>document.getElementById(id);
const token=location.hash.slice(1);history.replaceState(null,'','/');
let project='',previewHash='',candidateHash='',catalog=[],changes=[],busy=false,runningCandidates=[];
let setupHash='';
const message=(text,error=false)=>{$('message').textContent=text;$('message').dataset.error=String(error);};
async function api(action,fields={}){const response=await fetch('/api',{method:'POST',headers:{'content-type':'application/json','x-stylecon-session':token},body:JSON.stringify({action,...fields})});const data=await response.json();if(!response.ok)throw new Error(data.error);return data;}
async function perform(work){
  if(busy)return;
  const initiatingControl=document.activeElement;
  busy=true;$('workspace-controls').disabled=true;
  document.body.setAttribute('aria-busy','true');message('Working locally…');
  try{await work();}
  catch(error){message(error.message,true);}
  finally{
    busy=false;$('workspace-controls').disabled=false;document.body.removeAttribute('aria-busy');
    const target=initiatingControl?.isConnected&&!initiatingControl.disabled&&initiatingControl.offsetParent!==null&&initiatingControl!==document.body?initiatingControl:$('message');
    target.focus({preventScroll:true});
  }
}
function option(value,label){const node=document.createElement('option');node.value=value;node.textContent=label;return node;}
function findingFacts(check,source){$('finding-facts').replaceChildren();for(const [label,value]of [['Element',check.selector??check.target],['Target label',check.target],['Source label',source??'Unmapped'],['Viewport',check.viewport?.width?`${check.viewport.width}px`:'Journey'],['Observed',check.observed],['Expected',check.expected??check.fix],['Guidance',check.fix],['Limitation',check.limitation??'See coverage summary']]){const term=document.createElement('dt'),detail=document.createElement('dd');term.textContent=label;detail.textContent=typeof value==='object'?Object.entries(value??{}).map(([key,item])=>`${key}: ${typeof item==='object'?JSON.stringify(item):item}`).join(' · '):String(value??'Not recorded');$('finding-facts').append(term,detail);}}
function filterChecks(){for(const row of $('findings').children)row.hidden=row.dataset.status==='pass'&&!$('show-passed').checked;}
$('show-passed').onchange=filterChecks;
function invalidate(){previewHash='';$('preview').hidden=true;candidateHash='';$('candidate').hidden=true;}
async function projects(){const result=await api('projects');$('project').replaceChildren(option('','Select a project'),...result.projects.map(p=>option(p.path,`${p.path} · ${p.configured?'configured':'choose targets'}`)));await selectProject();message(`${result.projects.length} local projects found.`);}
function clearSetupReview(){setupHash='';$('setup-review').hidden=true;}
function setupKind(){clearSetupReview();const vite=$('setup-kind').value==='vite';$('setup').hidden=vite;$('vite-setup').hidden=!vite;}
$('setup-kind').onchange=setupKind;
$('vite-setup').oninput=clearSetupReview;
$('vite-setup').onsubmit=event=>{event.preventDefault();perform(async()=>{
  clearSetupReview();const options=Object.fromEntries([...$('vite-setup').querySelectorAll('input')].map(input=>[input.name,input.value]));
  const preview=await api('setup-preview',{project,options});setupHash=preview.previewSha256;
  $('setup-scope').textContent=preview.scope;$('setup-rules').replaceChildren();
  for(const measurement of preview.measurements)for(const group of ['typography','spacing'])for(const [property,value]of Object.entries(measurement.expected[group])){
    const item=document.createElement('li');item.textContent=`${measurement.selector} · ${group}.${property} → ${value}`;$('setup-rules').append(item);
  }
  $('setup-json').textContent=JSON.stringify(preview.config,null,2);$('setup-hash').textContent=setupHash;$('setup-review').hidden=false;message('Review the resolved rules and configuration, then save. Browser targets are not yet verified.');
});};
$('save-setup').onclick=()=>perform(async()=>{await api('setup-save',{project,previewSha256:setupHash});await selectProject();});
function showCoverage(report){
  const coverage=summarizeCoverage(report);$('coverage-title').textContent=coverage.headline;$('coverage-counts').textContent=coverage.breakdown;
  $('coverage-scope').replaceChildren();for(const text of coverage.scope){const item=document.createElement('li');item.textContent=text;$('coverage-scope').append(item);}
  $('coverage-limits').replaceChildren();for(const text of coverage.limitations){const item=document.createElement('li');item.textContent=text;$('coverage-limits').append(item);}$('coverage-incomplete').hidden=!coverage.incomplete.length;$('coverage-reasons').replaceChildren();
  for(const reason of coverage.incomplete){const item=document.createElement('li');item.textContent=`${reason.target} · ${reason.check}${reason.viewport?' · '+reason.viewport+'px':''}: ${reason.reason} Next: ${reason.next}`;$('coverage-reasons').append(item);}
}
async function selectProject(){clearSetupReview();$('setup-choice').hidden=true;$('vite-setup').hidden=true;$('finding-detail').hidden=true;project=$('project').value;invalidate();$('results').hidden=true;$('correction').hidden=true;$('undo').hidden=true;$('targets').hidden=true;$('setup').hidden=true;$('run').disabled=!project;if(!project)return;const list=await api('projects');const selected=list.projects.find(p=>p.path===project);if(!selected?.configured){$('setup-choice').hidden=false;setupKind();$('run').disabled=true;message('Choose IDs for a static page, or select React / Vite to configure a production preview.');return;}$('project').selectedOptions[0].textContent=`${project} · configured`;const config=await api('config',{project});$('target-content').textContent=JSON.stringify({integration:config.integration??'static HTML',journey:config.journey,targetPaths:config.targetPaths,measurements:config.measurements},null,2);$('targets').hidden=false;message(config.schemaVersion===2?'Running application selected. Start its trusted Vite production preview before checking. Verified stylesheet corrections require a rebuild.':'Project ready. Its configured dialog and controls will be exercised.');}
function showResult(data){$('results').hidden=false;$('result-status').textContent=data.summary.status;$('result-status').dataset.status=data.summary.status;const report=data.result.report;showCoverage(report);$('finding-detail').hidden=true;$('result-title').textContent=`${report.checks.length} configured checks`;$('binding').textContent=`Source ${report.artifactSha256}\nConstitution ${report.specSha256}`;$('report-file').textContent=`Private evidence saved: ${data.reportFile}`;$('findings').replaceChildren();for(const check of report.checks){const row=document.createElement('tr');row.dataset.status=check.status;for(const text of [check.status,describeTarget(check),check.ruleId+(check.viewport?.width?` · ${check.viewport.width}px`:'')]){const cell=document.createElement('td');cell.textContent=text;row.append(cell);}const cell=document.createElement('td'),button=document.createElement('button');button.textContent='Inspect';button.addEventListener('click',()=>{$('finding-detail').hidden=false;findingFacts(check,data.targetPaths[check.target]);$('finding-json').textContent=JSON.stringify({...check,source:data.targetPaths[check.target]??'unmapped'},null,2);$('finding-detail').scrollIntoView({block:'nearest'});});cell.append(button);row.append(cell);$('findings').append(row);}$('show-passed').checked=report.status==='pass';filterChecks();runningCandidates=data.result.repair?.candidates??[];const paths=[...new Set((data.result.repair?.findings??[]).filter(f=>f.status==='fail').map(f=>f.path))];$('repair-path').replaceChildren(...(runningCandidates.length?runningCandidates.map(c=>option(c.id,`${c.selector} · ${c.property}: ${c.before} → ${c.after}`)):paths.map(p=>option(p,p))));$('before').disabled=$('after').disabled=runningCandidates.length>0;$('before').required=$('after').required=!runningCandidates.length;$('before').value=runningCandidates[0]?.before??'';$('after').value=runningCandidates[0]?.after??'';$('correction').hidden=!paths.length&&!runningCandidates.length;previewHash='';$('preview').hidden=true;message(data.summary.status==='pass'?'Configured checks passed. Evidence is scoped to these targets.':'Review highlighted findings and any incomplete checks.');}
$('refresh').onclick=()=>perform(projects);$('project').onchange=()=>perform(selectProject);
function clearCheckEvidence(){previewHash='';for(const id of ['results','finding-detail','correction','preview'])$(id).hidden=true;}
async function checkProject(){clearCheckEvidence();showResult(await api('check',{project}));}
$('run').onclick=()=>perform(checkProject);
$('setup').onsubmit=event=>{event.preventDefault();perform(async()=>{const options={};for(const input of $('setup').querySelectorAll('input'))options[input.name]=input.value;await api('init',{project,options});await selectProject();});};
$('correction').onsubmit=event=>{event.preventDefault();perform(async()=>{const preview=await api('preview',{project,change:runningCandidates.length?{candidateId:$('repair-path').value}:{path:$('repair-path').value,before:$('before').value,after:$('after').value}});previewHash=preview.previewSha256;$('diff').textContent=typeof preview.diff==='string'?preview.diff:JSON.stringify(preview.diff,null,2);$('preview-hash').textContent=previewHash;$('preview').hidden=false;message('Review the exact change. Apply only if this is the correction you intend.');});};
for(const id of ['before','after','repair-path'])$(id).oninput=()=>{previewHash='';$('preview').hidden=true;if(runningCandidates.length){const selected=runningCandidates.find(c=>c.id===$('repair-path').value);$('before').value=selected?.before??'';$('after').value=selected?.after??'';}};
$('apply').onclick=()=>perform(async()=>{const applied=await api('apply',{project,previewSha256:previewHash});$('preview').hidden=true;$('correction').hidden=true;$('undo').hidden=false;if(applied.requiresRebuild){$('results').hidden=true;message('Source corrected. Rebuild your trusted Vite project, then Run checks. Undo is available.');return;}await checkProject();message('Correction applied and rechecked. Inspect the new result; undo is available.');});
$('undo').onclick=()=>perform(async()=>{const undone=await api('undo',{project});$('undo').hidden=true;if(undone.requiresRebuild){$('results').hidden=true;$('correction').hidden=true;$('preview').hidden=true;message('Original source restored. Rebuild your trusted Vite project, then Run checks.');return;}await checkProject();message('Original source restored and rechecked.');});
for(const name of ['checks','constitution'])$(name+'-nav').onclick=()=>{for(const id of ['checks','constitution']){$(id).hidden=id!==name;$(id+'-nav').classList.toggle('active',id===name);}};
function tokenValue(){const item=catalog.find(c=>c.path===$('token-path').value);$('token-value').value=item?.value??'';$('token-current').textContent=`Current value: ${item?.value??''}`;}
function renderChanges(){candidateHash='';$('candidate').hidden=true;$('changes').replaceChildren();for(const change of changes){const li=document.createElement('li');li.textContent=`${change.path} → ${change.value}`;$('changes').append(li);}if(!changes.length){const li=document.createElement('li');li.textContent='No changes selected.';$('changes').append(li);}}
$('load-catalog').onsubmit=event=>{event.preventDefault();perform(async()=>{catalog=(await api('catalog',{source:$('source').value})).items;$('token-path').replaceChildren(...catalog.map(item=>option(item.path,item.path.replace('tokens.','').replace('.$value',''))));$('token-editor').hidden=false;changes=[];renderChanges();tokenValue();message('Canonical rules loaded. Select changes for review.');});};
$('source').oninput=()=>{catalog=[];changes=[];renderChanges();$('token-editor').hidden=true;};$('token-path').onchange=tokenValue;
$('token-editor').onsubmit=event=>{event.preventDefault();const item=catalog.find(c=>c.path===$('token-path').value);const value=typeof item.value==='number'?Number($('token-value').value):$('token-value').value;changes=changes.filter(c=>c.path!==item.path);changes.push({path:item.path,value});renderChanges();message('Change added for validation and review.');};
$('clear-changes').onclick=()=>{changes=[];renderChanges();};
$('import-css').onclick=()=>perform(async()=>{const result=await api('import',{css:$('css').value});$('suggestions').replaceChildren();for(const suggestion of result.suggestions){const row=document.createElement('div');row.textContent=`${suggestion.provenance.variable}: ${suggestion.value} → ${suggestion.path} `;const button=document.createElement('button');button.className='quiet';button.textContent='Add to review';button.disabled=!catalog.some(item=>item.path===suggestion.path);button.onclick=()=>{changes=changes.filter(c=>c.path!==suggestion.path);changes.push({path:suggestion.path,value:suggestion.value});renderChanges();button.disabled=true;};row.append(button);$('suggestions').append(row);}const note=document.createElement('p');note.textContent=`${result.unmapped.length} variables have no supported mapping. Suggestions are not approved rules.`;$('suggestions').append(note);message('Review each imported suggestion before adding it.');});
$('review-rules').onclick=()=>perform(async()=>{const rule=$('exception-rule').value,target=$('exception-target').value,reason=$('exception-reason').value;const data=await api('candidate',{source:$('source').value,changes,exceptions:rule||target||reason?[{rule,target,reason}]:[]});candidateHash=data.candidateSha256;$('candidate-diff').textContent=JSON.stringify({changes:data.beforeAfterDiff,exceptions:data.exceptions},null,2);$('candidate-hash').textContent=candidateHash;$('candidate').hidden=false;message('Candidate validated. Review changes and approve this exact hash to export.');});
for(const id of ['exception-rule','exception-target','exception-reason'])$(id).oninput=()=>{candidateHash='';$('candidate').hidden=true;};
$('export-rules').onclick=()=>perform(async()=>{await api('export',{candidateSha256:candidateHash,destination:$('destination').value});$('candidate').hidden=true;message('Approved constitution exported to a new directory. Pin that copy explicitly in your project configuration.');});
if(token)perform(projects);else message('Open the complete local Studio link printed by the CLI, including its session fragment.',true);
