/* global document */
import {mkdtemp,mkdir,readFile,cp,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {prepareDemo} from './prepare-demo.mjs';
const {startStudio}=await import(process.argv[3]?pathToFileURL(resolve(process.argv[3])).href:'./studio.mjs');

const root=await mkdtemp(join(tmpdir(),'stylecon-studio-proof-'));
const workspace=join(root,'workspace'),evidence=join(root,'evidence');await mkdir(workspace);await mkdir(evidence);
const demo=await prepareDemo(join(workspace,'demo'));
const change=JSON.parse(await readFile(demo.change,'utf8'));
await mkdir(join(workspace,'unconfigured'));await cp(join(workspace,'demo/project/index.html'),join(workspace,'unconfigured/index.html'));
await mkdir(join(workspace,'rules'));await cp(fileURLToPath(new URL('../spec',import.meta.url)),join(workspace,'rules/spec'),{recursive:true});
let studio=await startStudio({workspace,evidenceDirectory:evidence});
const browser=await chromium.launch({headless:true});const errors=[];
const screenshots=process.argv[2]?resolve(process.argv[2]):evidence;
const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',error=>errors.push(error.message));page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text());});
const message=text=>page.getByRole('status').filter({hasText:text}).waitFor({timeout:60000});
try {
  await page.goto(studio.url);await message('local projects found');assert.match(await page.title(),/Local Studio/);
  await page.getByLabel('Project',{exact:true}).selectOption('unconfigured');await message('Choose IDs');
  for(const [name,value]of [['trigger','#review'],['dialog','#review-dialog'],['close','#back'],['name','Confirm display name']])await page.locator(`#setup input[name="${name}"]`).fill(value);
  await page.getByRole('button',{name:'Create configuration',exact:true}).click();await message('Project ready');assert.equal(JSON.parse(await readFile(join(workspace,'unconfigured/project.json'),'utf8')).journey.trigger,'#review');
  await page.getByLabel('Project',{exact:true}).selectOption('demo/project');await message('Project ready');
  await page.getByRole('button',{name:'Run checks',exact:true}).click();await message('Review highlighted findings');
  assert.equal(await page.locator('#result-status').textContent(),'fail');assert.equal(await page.locator('tr[data-status="fail"]').count(),1);
  await page.getByRole('button',{name:'Prepare review packet',exact:true}).click();await message('Review packet prepared');
  const review=JSON.parse(await page.locator('#review-data').textContent());
  assert.equal(review.counts.fail,1);assert.doesNotMatch(JSON.stringify(review),/#review|index.html|Studio member/);
  assert.equal(await page.getByRole('button',{name:'Download HTML review',exact:true}).isDisabled(),true);
  await page.getByLabel("I reviewed this packet's contents before download",{exact:true}).check();
  const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Download HTML review',exact:true}).click();
  const download=await downloaded,reviewPath=join(screenshots,'review.html');await download.saveAs(reviewPath);await message('Reviewed packet downloaded');
  const recipient=await browser.newPage({viewport:{width:1440,height:1000},javaScriptEnabled:false});const remoteRequests=[];
  recipient.on('request',request=>{if(/^https?:/.test(request.url()))remoteRequests.push(request.url());});
  await recipient.goto(pathToFileURL(reviewPath).href);assert.equal(await recipient.locator('article.check').count(),review.scope.total);
  assert.match(await recipient.locator('body').textContent(),/not a signature/);assert.equal(await recipient.locator('script,iframe,img,form').count(),0);
  await recipient.screenshot({path:join(screenshots,'review-desktop.png'),fullPage:true});await recipient.setViewportSize({width:390,height:844});
  assert.equal(await recipient.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true);
  await recipient.screenshot({path:join(screenshots,'review-mobile.png'),fullPage:true});assert.deepEqual(remoteRequests,[]);await recipient.close();
  const projectHtml=join(workspace,'demo/project/index.html'),originalHtml=await readFile(projectHtml,'utf8');
  let unexpectedDownloads=0;const onUnexpected=()=>unexpectedDownloads++;page.on('download',onUnexpected);
  await writeFile(projectHtml,originalHtml+'\n<!-- changed after review -->');
  const errorsBeforeRefusal=errors.length;
  const refusal=page.waitForResponse(response=>response.url()===studio.origin+'/api'&&response.request().postDataJSON()?.action==='review-download');
  await page.getByRole('button',{name:'Download HTML review',exact:true}).click();await message('stale');
  assert.equal((await refusal).status(),400);
  assert.deepEqual(errors.splice(errorsBeforeRefusal),['Failed to load resource: the server responded with a status of 400 (Bad Request)']);
  assert.equal(await page.locator('#review-preview').isHidden(),true);assert.equal(unexpectedDownloads,0);
  page.off('download',onUnexpected);await writeFile(projectHtml,originalHtml);
  await page.locator('tr[data-status="fail"]').getByRole('button',{name:'Inspect'}).click();assert.match(await page.locator('#finding-json').textContent(),/observed/);
  await page.locator('tr[data-status="fail"] input[type="checkbox"]').check();
  await page.getByRole('button',{name:'Prepare selected findings',exact:true}).click();await message('Brief prepared');
  const brief=await page.getByLabel('Agent brief',{exact:true}).inputValue();assert.match(brief,/artifactSha256/);assert.match(brief,/projectConfigurationSha256/);assert.doesNotMatch(brief,/<!doctype|receiptPath|x-stylecon-session/i);
  await page.evaluate(()=>Object.defineProperty(globalThis.navigator,'clipboard',{value:{writeText:async text=>{globalThis.__brief=text;}},configurable:true}));
  await page.getByRole('button',{name:'Copy reviewed brief',exact:true}).click();await message('Reviewed brief copied');assert.equal(await page.evaluate(()=>globalThis.__brief),brief);
  await page.screenshot({path:join(screenshots,'studio-desktop.png'),fullPage:true});
  await page.getByLabel('Current text',{exact:true}).fill(change.before);await page.getByLabel('Replacement text',{exact:true}).fill(change.after);
  await page.getByRole('button',{name:'Preview correction',exact:true}).click();await message('Review the exact change');
  await page.getByRole('button',{name:'Apply this correction',exact:true}).click();await message('Correction applied and rechecked');assert.equal(await page.locator('#result-status').textContent(),'pass');
  await page.locator('#run-history summary').click();await page.getByRole('button',{name:'Compare these runs',exact:true}).click();await message('Historical comparison ready');
  const comparison=JSON.parse(await page.locator('#comparison-details').textContent());assert.equal(comparison.resolved.length,1);assert.equal(comparison.incomplete.length,0);
  await page.getByRole('button',{name:'Undo last correction',exact:true}).click();await message('Original source restored and rechecked');assert.equal(await page.locator('#result-status').textContent(),'fail');
  await page.getByRole('button',{name:'02 · Create rules',exact:true}).click();await page.getByLabel('Constitution repository, relative to workspace').fill('rules');await page.getByRole('button',{name:'Load canonical rules'}).click();await message('Canonical rules loaded');
  await page.getByLabel('Rule',{exact:true}).selectOption('tokens.space.4.$value');await page.getByLabel('New value',{exact:true}).fill('20px');await page.getByRole('button',{name:'Add to review',exact:true}).click();
  await page.getByLabel('Rule',{exact:true}).selectOption('components.button.accessibility.minimumTarget');await page.getByLabel('New value',{exact:true}).fill('48px');await page.getByRole('button',{name:'Add to review',exact:true}).click();
  await page.getByRole('button',{name:'Validate & review candidate'}).click();await message('Candidate validated');
  await page.getByLabel('New export directory, relative to workspace').fill('team-rules');await page.getByRole('button',{name:'Approve this hash & export'}).click();await message('Approved constitution exported');
  const exported=JSON.parse(await readFile(join(workspace,'team-rules/spec/tokens/primitive.json'),'utf8'));assert.equal(exported.space['4'].$value,'20px');
  await page.getByRole('button',{name:'01 · Check & correct',exact:true}).click();
  await page.locator('#project-rules > details > summary').click();await page.getByText('Create a snapshot from canonical rules',{exact:true}).click();
  await page.getByRole('button',{name:'Create new snapshot',exact:true}).click();await message('New snapshot created');
  await page.getByRole('button',{name:'Review rule adoption',exact:true}).click();await message('Review the rule changes');assert.match(await page.locator('#adoption-diff').textContent(),/48/);
  await page.getByRole('button',{name:'Adopt these reviewed rules',exact:true}).click();await message('Reviewed rules adopted');assert.equal(await page.locator('#results').isHidden(),true);
  await page.getByRole('button',{name:'Run checks',exact:true}).click();await message('Review highlighted findings');
  const ruleFinding=await page.locator('tr[data-status="fail"]').first();await ruleFinding.getByRole('button',{name:'Inspect'}).click();assert.match(await page.locator('#finding-json').textContent(),/48/);
  await page.getByRole('button',{name:'Compare these runs',exact:true}).click();await message('These runs cannot establish resolution');
  // Restart with the same private directory: historical views are available without live authority.
  await studio.close();studio=await startStudio({workspace,evidenceDirectory:evidence});await page.goto(studio.url);await message('local projects found');
  await page.getByLabel('Project',{exact:true}).selectOption('demo/project');await message('Project ready');
  assert.equal(await page.locator('#history-head option').count(),4);await page.locator('#run-history summary').click();
  await page.getByRole('button',{name:'Open selected later run',exact:true}).click();await message('Historical evidence opened');
  assert.match(await page.locator('#result-title').textContent(),/Historical observation/);assert.equal(await page.locator('#correction').isHidden(),true);assert.equal(await page.locator('#agent-handoff').isHidden(),true);assert.equal(await page.locator('#review-handoff').isHidden(),true);
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:join(screenshots,'studio-mobile.png'),fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth),true);
  await page.keyboard.press('Tab');assert.notEqual(await page.evaluate(()=>document.activeElement.tagName),'BODY');
  assert.deepEqual(errors,[]);
  const receipt={passed:true,cases:['render desktop/mobile','configured targets','real browser failure','offline HTML download with every result and private markers absent','desktop/mobile recipient view with JavaScript disabled and zero network requests','changed source blocks download and clears preview','finding details','selected private agent brief and copy','exact preview','apply and real recheck','same-scope resolved comparison','undo and real recheck','canonical authoring and approved export','snapshot creation and reviewed 48px rule adoption','different-rules comparison refused','restart and historical evidence without repair or review authority','no horizontal overflow','keyboard focus','no runtime console errors'],privateEvidence:evidence,screenshots};
  await writeFile(join(evidence,'studio-qa.json'),JSON.stringify(receipt,null,2));console.log(JSON.stringify(receipt));
}catch(error){console.error('Studio visible state:',await page.locator('#message').textContent());console.error('Browser errors:',JSON.stringify(errors));throw error;}finally{await browser.close();await studio.close();}
